services:
  server:
    image: 632872792512.dkr.ecr.us-east-1.amazonaws.com/bia:${TAG}
    container_name: bia
    ports:
      - 80:8080
    environment:
      DB_PORT: 5432
      DB_HOST: bia-db-loadbalancer.cmrs262sykb3.us-east-1.rds.amazonaws.com
      DB_SECRET_NAME: rds!db-4cebde56-b851-4e9c-ab8f-ab20a80427f0
      DB_REGION: us-east-1